---
redis:
  # The Redis hostname
  host: "redis"
  # The Redis port number
  port: 6379
  # The RPQ Redis namespace
  namespace: "rpq"

# The PID file location
pid: ./rpq.pid

# Jobs will execute in process mode
mode: process

log:
  # The path to a PHP file that returns an instance Monolog\Logger;
  logger: null
  # The MonoLog log level
  level: DEBUG

process:
  # The process script name. Defaults to PHP `$_SERVER['SCRIPT_FILENAME']
  # This option enables you to define a custom entry point for your command with integration with other frameworks
  script: null
  # The CLI command to call
  command: 'worker/process'
  # Whether or not to include the path to the RPQ configuration file.
  # This option may be set to false for framework integratiion
  config: true

queue:
  # `default` is the default queue all jobs are pushed in to
  default:
    # The maximum number of jobs to spawn. In process mode, this is the maxmimum number of sub-process workers that will run
    max_jobs: 20
    # In milliseconds, the polling interval to fetch new jobs
    poll_interval: 100
    # When SIGQUIT is set to the process, how much time to allow a process to shutdown before forcefully killing it
    deadline_timeout: 10
    # Number of seconds failed jobs should be backed off before attempting again.
    # This can help avoid excessive CPU usaging when a stuck job without a retry limit fails repeatedly
    failed_job_backoff_time: 10