#!/usr/bin/env php
<?php declare(strict_types=1);

$paths = [
    __DIR__ . '/autoload.php',
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../../../autoload.php'
];

foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}

use Symfony\Component\Console\Application;
use RPQ\Queue\Command\QueueCommand;
use RPQ\Queue\Command\WorkerCommand;

$version = 'dev';
if (\file_exists('.git/refs/heads/master')) {
    $version = \file_get_contents(sprintf('.git/refs/heads/%s', 'master'));
}

$app = new Application('rpq', $version);
$queueCommand = new QueueCommand;
$workerCommand = new WorkerCommand;

$app->add($workerCommand);
$app->add($queueCommand);
$app->setDefaultCommand($queueCommand->getName());
$app->run();